### PR TITLE
Update continuous-integration.yml

### PR DESCRIPTION
**Pull request by simsong**

### CODE REVIEW

**Comment by catap** [comment]
FYI: you may add some other systems to CI: https://github.com/vmactions

**Comment by simsong** [comment]
If you would like to submit the CI/CDs, I would appreciate it. I'm having problems with this at the moment, although I don't know why.

**Comment by simsong** [comment]
Looks like the detection for libssl no longer works:
```
configure: error: OpenSSL developer library 'libssl-dev' or 'openssl-devel' not installed
checking for OPENSSL_init_ssl in -lssl... no
Error: Process completed with exit code 1.
```

But i really don't have time to fix this at the moment.

**Comment by catap** [comment]
@simsong I'm looking right now

**Comment by catap** [comment]
@simsong now you need to update this branch

**Comment by simsong** [comment]
Okay...

**Pull request merged**
