### PR TITLE
Adding option -u for libpcap update timeout

### PR DESCRIPTION
**Pull request by emanuelen5**
Adding an option, -u, for setting a custom libpcap update timeout
in milliseconds (only for live monitoring)

### CODE REVIEW

**Comment by simsong** [comment]
I would much rather do this with a name=value preference, rather than using -t for it. Can you do it that way instead?

**Comment by emanuelen5** [comment]
Like a long option `--packet-buffer-timeout`?

**Comment by simsong** [comment]
There is a whole name=value system for setting arbitrary options.

**Comment by emanuelen5** [comment]
Ok, I'll look at it

**Comment by emanuelen5** [comment]
Like https://github.com/emanuelen5/tcpflow/commit/e6c48279e265984ce3ea009925c8a9b1bb50d2db (i.e. `-S packet-buffer-timeout=20`)?

**Comment by simsong** [comment]
Precisely! (I wrote this code years ago, but we should try to follow the system. Unless you want to make it all use gnu getopt syntax. But I find that tiresome...)

**Comment by emanuelen5** [comment]
Let's close this pull request and open for the other one instead then :)

**Comment by simsong** [comment]
Sounds good. It's great to work with you!.

**Pull request closed without merging**
