### PR TITLE
Update README for 1.4.5

### PR DESCRIPTION
**Pull request by md5**
This can be merged once the 1.4.5 release tarball and ZIP are pushed.

### CODE REVIEW

**Comment by md5** [comment]
@simsong Any chance you'll have some time next week to do a release?

**Comment by simsong** [comment]
What do you want in the release?

**Comment by md5** [comment]
I was interested in the changes from #74 (*tcpflow prints "write error to stdout" after every packet*). I haven't reviewed the other changes since the last release thoroughly.

In all honesty, I was just looking through my open PRs and thought I'd follow up. There isn't an urgent need for the changes in #74 since it's a harmless (though annoying) error message.

**Comment by simsong** [comment]
The release is tagged, it's just not available for download. Is that what you need?

**Comment by md5** [comment]
Yes. My goal is to submit an update to Alpine Linux to have the latest
version included. They currently pull from your packaged releases.

**Comment by md5** [comment]
@simsong Just wanted to follow up again on getting a packaged download for 1.4.5 so I can submit a change to Alpine Linux.

Thanks! :+1:

**Comment by simsong** [comment]
Did you check the download site? It should be there.

**Comment by md5** [comment]
Thanks! I should have checked first. Sorry about that.

Do you want me to leave this PR open? Looks like the `README.md` could still stand to be updated.

**Comment by simsong** [comment]
If you want to update the README.me, that would be great.

**Comment by md5** [comment]
Cool. I think this PR should cover it! :+1:

**Comment by md5** [comment]
FYI, the Alpine folks have updated to 1.4.5: http://git.alpinelinux.org/cgit/aports/commit/?id=75149aec8f73b5d2e750eebac8bfbf28df8452c0

**Comment by md5** [comment]
Sorry, linked to the wrong diff: http://git.alpinelinux.org/cgit/aports/commit/?id=e6a76917b3439ee7837f07cd680a8a8d1ba3c179

Looks like they also ended up needing to patch `tcpflow` due to differences between `musl` and `glibc`: http://git.alpinelinux.org/cgit/aports/commit/?id=ffda174b5508f59adbe44547cc97e7a1c436671e

**Comment by simsong** [comment]
Okay. Thanks!

**Pull request closed without merging**
