### PR TITLE
Add a new scanner to call external python script

### PR DESCRIPTION
**Pull request by olibre**
The objective is to empower DevOps by allowing to extend tcpflow using python language.

The original work is available on @lassimus' fork:
https://github.com/lassimus/tcpflow/commits/master

I have continued the work, kept this great idea, but I had to deeply refactored the source code.
Instead of introducing a new option `-P`, my proposal reuses option `-e python` and adds three parameters `-S py_path=... -S py_module=... -S py_function=...`.
Same for the Autotools/Automake files and CMake files that have been fixed.

For the Autotools/Automake side, the project builds fine with and without the package python-devel. However for CMake build, package python-devel is required (I do not want to maintain to build systems in parallel, but I dream to use only CMake).

The resulted executable `tcpflow` have been tested in many ways: built with and without python-devel installation, options `-a`, `-e python`, missing parameters, mistakes in parameters...

Please review the source code, performs many tests on your side, and find issues ;-)
Does the added/modified source fit with the tcpflow code style spirit?

There are also some TODOs withing the source code assigned to you (@simsong):

- [TODO #1](https://github.com/olibre/tcpflow/blob/scan_python/src/scan_python.cpp#L107) When the scanner cannot initialize it, should we use `sp.info->flags = scanner_info::SCANNER_DISABLED`?
- [TODO #2](https://github.com/olibre/tcpflow/blob/scan_python/src/scan_python.cpp#L153) Why PHASE_THREAD_BEFORE_SCAN never called?
- [TODO #3](https://github.com/olibre/tcpflow/blob/scan_python/src/scan_python.cpp#L167) Similar to TODO #1

I hope this new feature will amplify the possibilities of tcpflow output data processing :smiley:

### CODE REVIEW

**Comment by olibre** [comment]
Just dicovered the DFXML schema `dfxml.xsd` on Git repo https://github.com/dfxml-working-group/dfxml_schema

We need to check if the XML tag `<scan_python_result>` is OK and if not, what to use...

**Comment by simsong** [comment]
Or we can modify the dfxml_schema.

**Comment by olibre** [comment]
> Or we can modify the dfxml_schema.

Good idea, we could have a more generic `<result>` tag:

    <result scanner="python">bla bla bla</result>

    <result scanner="http">bla bla bla</result>

**Comment by simsong** [comment]
So let's figure the correct scheme, and then send a push to the other project. We can even add it as a sub project, if you wish.


----
Sent from my phone.

On Jun 5, 2017, at 2:29 AM, O. Libre <notifications@github.com> wrote:

Or we can modify the dfxml_schema.

Good idea, we could have a more generic <result> tag:

<result scanner="python">bla bla bla</result>

<result scanner="http">bla bla bla</result>

**Comment by olibre** [comment]
What do you suggest about XML tag improvements on reflection https://github.com/dfxml-working-group/dfxml_schema/issues/24?

**Comment by olibre** [comment]
This pull request is replaced by https://github.com/simsong/tcpflow/pull/164

**Pull request closed without merging**
