### PR TITLE
Added FreeBSD and OpenBSD, and install missed cairo on macOS

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by simsong** [comment]
Any idea why the CI/CD is not running for your PRs? On other repos, I'm given the option of Actions when there is a PR from someon who is not in the project.

**Comment by simsong** [comment]
found the bug. I need to rename master to main. Standby...

**Comment by catap** [comment]
@simsong seems that it works

**Comment by simsong** [comment]
@catap  - thanks for your help on this!

**Pull request merged**
