### PR TITLE
per flow pcap structure output

### PR DESCRIPTION
**Pull request by cherusk**
Shall provide an alternative processing pkt path
for extruding isolated pcap flows for processing
stacked upon tcpflow lower level logic.

Signed-off-by: Matthias Tafelmeier <matthias.tafelmeier@gmx.net>

### CODE REVIEW

**Comment by simsong** [comment]
What is the glitch and can we fix it?


----
Sent from my phone.

On Dec 9, 2018, at 5:04 AM, Matthias Tafelmeier <notifications@github.com> wrote:

This is working smoothly, despite glibc glitch[1] encountered on fedora28/29, out of scope of tcpflow and this PR of course.

[1]
Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x00007fa95f2ea895 in __strlen_avx2 () from /lib64/libc.so.6

**Comment by simsong** [comment]
I do not want to accept a pull request with a known segmentation fault. No input should be able to make the program crash. Is this segmentation fault in the master branch? Do you have input that reliably exhibits the SIGSEGV?

**Comment by simsong** [comment]
But I have looked at your code and it doesn't seem likely that your code is causing the crash. Any ideas?

**Comment by cherusk** [comment]
Could be something trivial.

By adding dbg lines, I could confine it to the bold line in src/tcpflow.cpp

886-	demux.start_new_connections = true;
887-        int err = process_infile(demux,expression,device,"");
888-        if (err < 0) {
889-            exit_val = 1;
890-        }
**891:        input_fname = device;**
892-    }
893-    else {

**Comment by simsong** [comment]
That looks like something I can fix tonight..

**Pull request merged**
